#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, with a special message on the 9th iteration

i=0
while [ $i -lt 10 ]; do
  if [ $i -eq 8 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  i=$((i+1))
done
